### PR TITLE
Upgrade Lottie to 4.4.3.

### PR DESCRIPTION
**Pull request by TomerHacohen**
This xcframework was built from the Lightricks's fork of Lottie: https://github.com/Lightricks/lottie-ios/ by using the tag `4.4.3`.

The log can be found here:
https://github.com/Lightricks/Foundations/actions/runs/9751329317

### CODE REVIEW

**Comment by TamarMilchtaich** [comment]
Did you try it with one of the apps to make sure the animation looks OK?

**Comment by barakwei** [comment]
Use the same commit message as the previous versions

**Comment by TomerHacohen** [comment]
@barakwei, which log if I built it locally?
@TamarMilchtaich I tested 3 animations I could find in VL and they all look good.

**Comment by barakwei** [comment]
We always build in CI, never ever ever locally.

**Comment by barakwei** [comment]
The reasoning is that locally there can be mistakes in the environment, and in CI it's more sterile and more clear, theoretically in the logs you can see the commit hash, see exactly what's the Xcode version etc. Kinda shitty that the logs get deleted, but I trust an existing script over you 😄

**Comment by TomerHacohen** [comment]
That's make sense, thanks

**Comment by TomerHacohen** [comment]
Fixed and squashed.

**Pull request merged**
